### ISSUE TITLE
Error with FluentC++ Feed: Failed to parse time string (max-age=2592000, public)

### ISSUE THREAD

**Issue by lx-s** [fguillot/picoFeed#337]
Hi,

I encountered the following error, when I tried to add the [FluentCpp Feed](http://www.fluentcpp.com/feed/) to Miniflux: 
```
Uncaught Exception: DateTime::__construct(): Failed to parse time string (max-age=2592000, public) at position 0 (m): The timezone could not be found in the database in miniflux/vendor/fguillot/picofeed/lib/PicoFeed/Client/Client.php:699
Stack trace:
#0 miniflux/vendor/fguillot/picofeed/lib/PicoFeed/Client/Client.php(699): DateTime->__construct('max-age=2592000...')
#1 miniflux/vendor/fguillot/picofeed/lib/PicoFeed/Client/Client.php(225): PicoFeed\Client\Client->parseExpiration(Object(PicoFeed\Client\HttpHeaders))
#2 miniflux/vendor/fguillot/picofeed/lib/PicoFeed/Reader/Reader.php(53): PicoFeed\Client\Client->execute('http://www.flue...')
#3 miniflux/vendor/fguillot/picofeed/lib/PicoFeed/Reader/Reader.php(69): PicoFeed\Reader\Reader->download('http://www.flue...', NULL, NULL, '', '') in miniflux/vendor/fguillot/picofeed/lib/PicoFeed/Client/Client.php on line 699
```

I added a `print_r($header);` statement at the top of `parseExpiration()`, to get more Information:
```
PicoFeed\Client\HttpHeaders Object
(
    [headers:PicoFeed\Client\HttpHeaders:private] => Array
        (
            [server] => nginx/1.12.0
            [date] => Tue, 06 Jun 2017 10:36:09 GMT
            [content-type] => application/rss+xml; charset=UTF-8
            [content-length] => 44162
            [connection] => close
            [etag] => "cd595f0b4da900af27c43cb0cb91f4ef"
            [x-robots-tag] => noindex, follow
            [link] => <http://www.fluentcpp.com/wp-json/>; rel="https://api.w.org/"
            [last-modified] => Tue, 06 Jun 2017 03:20:33 GMT
            [vary] => Accept-Encoding
            [content-encoding] => gzip
            [expires] => max-age=2592000, public
            [x-acc-exp] => 600
            [x-proxy-cache] => MISS www.fluentcpp.com
        )
)
```
This prevents running Miniflux' Cronjob as well. Thanks for your help!

**Comment by JKingweb** [comment]
While picoFeed should not be producing an error here, the server is unquestionably broken: it is sending an Expires header-field when what it clearly intended to send was Cache-Control.
